# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Clock_Divider.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Decod_Piso.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Decoder.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/FSM.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Motor_Ascensor.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Motor_Puerta.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Sim_Piso.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Sim_Puerta.vhd
  C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/sources_1/new/Top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/constrs_1/imports/Ascensor/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Luis/Documents/GitHub/Ascensor/project_1/project_1.srcs/constrs_1/imports/Ascensor/Nexys-4-DDR-Master.xdc]


synth_design -top Top -part xc7k70tfbv676-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
